apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orderupdate
spec:
  type: bindings.rabbitmq
  version: v1
  metadata:
  - name: queueName
    value: bindQueue
  - name: host
    value: amqp://admin:!2021que@rabbitmq:5672
  - name: durable
    value: true
  - name: deleteWhenUnused
    value: false
  - name: ttlInSeconds
    value: 60
  - name: prefetchCount
    value: 0
  - name: exclusive
    value: false
  - name: maxPriority
    value: 5    